# Generated by Django 3.1.3 on 2022-09-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_alter_game_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
